project:
  type: website
  resources:
    - "images/twitter-card.png"

execute:
  freeze: true

website:
  title: "蜡笔小周的博客"
  site-url: https://pkuzzq.netlify.app/
  twitter-card:
    creator: "@Bioconductor"
    image: "/images/twitter-card.png"
  open-graph: true
  page-footer:
    left: "Blog made with Quarto."
    right:
      - icon: github
        href: https://github.com/pkuzzq/
      - icon: twitter
        href: https://twitter.com/pkuzzq12345
      - icon: envelope
        href: mailto:pkuzzq@pku.edu.cn
  navbar:
    title: "蜡笔小周的博客"
    background: "#43418A"
    foreground: "#000000"
    pinned: true
    left:
    - text: "Jason ZHOU"
    right:
      - about.qmd
      - text: Posts
        href: post/
      - text: DataMethods
        href: datamethods.qmd
      - text: Publications
        href: https://www.zotero.org/groups/feh/items/q/Harrell
      - icon: github
        href: https://github.com/pkuzzq
      - icon: twitter
        href: https://twitter.com/pkuzzq12345
  
format:
  html:
    smooth-scroll: true
    theme: [litera, styles.scss]
    css: xaringan-themer.css
    link-external-icon: false
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    toc-depth: 3
    toc-title: Contents
    toc-location: left
    code-link: false
    anchor-sections: true
    code-tools: true
    code-fold: true
    code-block-bg: "#f1f3f5"
    code-block-border-left: "#31BAE9"
    reference-location: margin
    fig-cap-location: margin

comments:
  hypothesis:
    theme: clean
    openSidebar: false
    enableExperimentalNewNoteButton: true